java.lang.IllegalArgumentException: Argument unrecognized by ScalaTest's Runner: exists
	at org.scalatest.tools.Runner$.parseArgs(Runner.scala:1414)
	at org.scalatest.tools.Framework.runner(Framework.scala:1073)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:539)
	at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:533)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$.createTestRunners(Defaults.scala:533)
	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:549)
	at sbt.Defaults$$anonfun$inputTests0$1$$anonfun$apply$26.apply(Defaults.scala:522)
	at sbt.Defaults$$anonfun$inputTests0$1$$anonfun$apply$26.apply(Defaults.scala:513)
	at sbt.std.FullInstance$$anonfun$flattenFun$1$$anonfun$apply$4$$anonfun$apply$5.apply(TaskMacro.scala:61)
	at sbt.std.FullInstance$$anonfun$flattenFun$1$$anonfun$apply$4$$anonfun$apply$5.apply(TaskMacro.scala:61)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(test:[31mtestOnly[0m) java.lang.IllegalArgumentException: Argument unrecognized by ScalaTest's Runner: exists[0m
